name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t fumiq-api-nodejs .

      - name: Copy files to server via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          port: ${{ secrets.SERVER_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "dist/,package.json,.env"   # only necessary files
          target: "/home/${{ secrets.SERVER_USER }}/FUMIQ-API-NODEJS"

      - name: SSH into server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          port: ${{ secrets.SERVER_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/${{ secrets.SERVER_USER }}/FUMIQ-API-NODEJS
            sudo docker stop fumiq-api-nodejs || true
            sudo docker rm fumiq-api-nodejs || true
            sudo docker build -t fumiq-api-nodejs .
            sudo  docker run --env-file .env  -p 3009:3009  --name fumiq-api-nodejs fumiq-api-nodejs 
